-- V015: 扩展 base_items 表，完整映射 Wiki items Cargo 全部 78 个字段
-- 使用 ALTER TABLE ADD COLUMN 逐一添加新列，不破坏已有数据

ALTER TABLE base_items ADD COLUMN name_list TEXT;
ALTER TABLE base_items ADD COLUMN metadata_id TEXT;
ALTER TABLE base_items ADD COLUMN _page_name TEXT;
ALTER TABLE base_items ADD COLUMN class_id TEXT DEFAULT '';
ALTER TABLE base_items ADD COLUMN frame_type TEXT;
ALTER TABLE base_items ADD COLUMN rarity TEXT;
ALTER TABLE base_items ADD COLUMN rarity_id TEXT;
ALTER TABLE base_items ADD COLUMN base_item TEXT;
ALTER TABLE base_items ADD COLUMN base_item_id TEXT;
ALTER TABLE base_items ADD COLUMN base_item_page TEXT;
ALTER TABLE base_items ADD COLUMN size_x INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN size_y INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN inventory_icon TEXT;
ALTER TABLE base_items ADD COLUMN required_level INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN required_level_base INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN required_dexterity INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN required_intelligence INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN required_strength INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN required_level_range_average INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN required_level_range_colour TEXT;
ALTER TABLE base_items ADD COLUMN required_level_range_maximum INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN required_level_range_minimum INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN required_level_range_text TEXT;
ALTER TABLE base_items ADD COLUMN required_dexterity_range_average INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN required_dexterity_range_colour TEXT;
ALTER TABLE base_items ADD COLUMN required_dexterity_range_maximum INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN required_dexterity_range_minimum INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN required_dexterity_range_text TEXT;
ALTER TABLE base_items ADD COLUMN required_intelligence_range_average INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN required_intelligence_range_colour TEXT;
ALTER TABLE base_items ADD COLUMN required_intelligence_range_maximum INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN required_intelligence_range_minimum INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN required_intelligence_range_text TEXT;
ALTER TABLE base_items ADD COLUMN required_strength_range_average INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN required_strength_range_colour TEXT;
ALTER TABLE base_items ADD COLUMN required_strength_range_maximum INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN required_strength_range_minimum INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN required_strength_range_text TEXT;
ALTER TABLE base_items ADD COLUMN required_level_html TEXT;
ALTER TABLE base_items ADD COLUMN required_dexterity_html TEXT;
ALTER TABLE base_items ADD COLUMN required_intelligence_html TEXT;
ALTER TABLE base_items ADD COLUMN required_strength_html TEXT;
ALTER TABLE base_items ADD COLUMN drop_enabled INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN drop_level_maximum INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN is_account_bound INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN is_corrupted INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN is_drop_restricted INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN is_eater_of_worlds_item INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN is_fractured INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN is_in_game INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN is_replica INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN is_searing_exarch_item INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN is_synthesised INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN is_unmodifiable INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN is_veiled INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN stat_text TEXT;
ALTER TABLE base_items ADD COLUMN explicit_stat_text TEXT;
ALTER TABLE base_items ADD COLUMN implicit_stat_text TEXT;
ALTER TABLE base_items ADD COLUMN drop_text TEXT;
ALTER TABLE base_items ADD COLUMN drop_areas TEXT;
ALTER TABLE base_items ADD COLUMN drop_areas_html TEXT;
ALTER TABLE base_items ADD COLUMN drop_monsters TEXT;
ALTER TABLE base_items ADD COLUMN drop_rarity_ids TEXT;
ALTER TABLE base_items ADD COLUMN tags TEXT;
ALTER TABLE base_items ADD COLUMN acquisition_tags TEXT;
ALTER TABLE base_items ADD COLUMN influences TEXT;
ALTER TABLE base_items ADD COLUMN description TEXT;
ALTER TABLE base_items ADD COLUMN help_text TEXT;
ALTER TABLE base_items ADD COLUMN html TEXT;
ALTER TABLE base_items ADD COLUMN infobox_html TEXT;
ALTER TABLE base_items ADD COLUMN metabox_html TEXT;
ALTER TABLE base_items ADD COLUMN alternate_art_inventory_icons TEXT;
ALTER TABLE base_items ADD COLUMN quality INTEGER DEFAULT 0;
ALTER TABLE base_items ADD COLUMN release_version TEXT;
ALTER TABLE base_items ADD COLUMN removal_version TEXT;

-- 重建索引（新字段索引）
CREATE INDEX IF NOT EXISTS idx_base_items_class_id ON base_items(class_id);
CREATE INDEX IF NOT EXISTS idx_base_items_rarity ON base_items(rarity);
CREATE INDEX IF NOT EXISTS idx_base_items_base_item ON base_items(base_item);
CREATE INDEX IF NOT EXISTS idx_base_items_is_in_game ON base_items(is_in_game);
